FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y \
        cmake \
        g++ \
        git \
        pkg-config \
        libboost-dev \
        libdocopt-dev \
        nlohmann-json3-dev
